import "@/app/globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/components/layout/providers";
import { auth } from "@/auth";
import getInquire from "@/actions/getInquire";
import InitProjects from "@/lib/initUser";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const projects = await getInquire();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <main className="flex h-screen w-full ">

            <Toaster />
            <div className="flex-1 overflow-hidden ">{children}</div>
          </main>
          <InitProjects projects={projects} />
        </Providers>
      </body>
    </html>
  );
}
