import type { Metadata } from "next";
import "../globals.css";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { MobileNavbar } from "@/components/homePage/mobile-nav";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/components/layout/providers";
import { auth } from "@/auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <Navbar className="hidden md:flex" />
          <MobileNavbar className="flex md:hidden" />
          <div className="container">
            <Toaster />
            {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
